name: Renovate
on:
  push:
    branches:
      - 'renovate/**'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-exists: ${{ steps.check.outputs.pr-exists }}
    steps:
      - name: Check if PR exists
        id: check
        uses: eliashaeussler/.github/actions/github/check-pr@1.1.0

  trigger-cgl:
    runs-on: ubuntu-latest
    needs: check-pr
    if: '!needs.check-pr.outputs.pr-exists'
    steps:
      - name: Trigger CGL workflow
        uses: eliashaeussler/.github/actions/github/trigger-workflow@1.1.0
        with:
          workflow: cgl.yaml
